Repository PrestaShop/kanbanbot, pull requests merged in 2023-06, with the labels that each got.

#10 Add webhook for github events
  Dockerfile
  composer.json
  composer.lock
  config/packages/framework.yaml
  config/routes/webhook.yaml
  config/services.php
  etc/apache_vhost.conf
  phpunit.xml.dist
  src/PullRequest/Infrastructure/Adapter/RestPullRequestRepository.php
  src/PullRequestDashboard/Infrastructure/Adapter/GraphqlGithubPullRequestCardRepository.php
  src/Shared/RemoteEvent/GithubConsumer.php
  src/Shared/Webhook/GithubWebhookParser.php
  symfony.lock
  tests/PullRequestDashboard/Infrastructure/Adapter/GraphqlGithubPullRequestCardRepositoryTest.php
  tests/Shared/Command/OnGithubEventCommandTest.php
  tests/Shared/Webhook/GithubWebhookTest.php
Labels: integration deployment

#11 Feat: production workflow
  .github/workflows/kanbanbot-production.yml
Labels: Waiting for QA

#13 Fix signature payload comparison
  src/Shared/Webhook/GithubWebhookParser.php
  tests/Shared/Webhook/GithubWebhookTest.php
Labels: Waiting for QA, integration deployment
